name: Bashar_RDP_Project

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Connect Tailscale
        shell: powershell
        run: |
          iwr -useb https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
          Start-Process .\tailscale-setup.exe -ArgumentList '/quiet' -Wait
          & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          
      - name: Configure RDP Access
        shell: powershell
        run: |
          # هنغير باسورد اليوزر الأصلي عشان منعملش يوزر جديد ونوجع دماغنا
          $Password = "Bashar_2026_Secure!"
          $User = "runneradmin"
          net user $User $Password
          echo "Password for $User updated successfully!"
          
      - name: Keep Alive
        run: |
          echo "Connect now using Tailscale IP"
          echo "User: runneradmin"
          echo "Pass: Bashar_2026_Secure!"
          sleep 21600
