name: Bashar_RDP_Project

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Preparing Environment
        run: |
          python --version
          
      - name: Connect Tailscale
        shell: powershell
        run: |
          iwr -useb https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
          Start-Process .\tailscale-setup.exe -ArgumentList '/quiet' -Wait
          & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          
      - name: Configure RDP User
        shell: powershell
        run: |
          # الباسورد الجديد (قوي جداً ومقبول): Bsh@r2026_Secure_RDP
          $name = "Bashar"
          $pass = "Bsh@r2026_Secure_RDP"
          net user $name $pass /add
          net localgroup Administrators $name /add
          net localgroup "Remote Desktop Users" $name /add
          echo "User Created Successfully!"
          
      - name: Keep Alive
        run: |
          echo "RDP is ready!"
          echo "User: Bashar"
          echo "Pass: Bsh@r2026_Secure_RDP"
          sleep 21600
